name: Docs, Webverion and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      #Documentation
    - name: Install packages for docs
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y doxygen
    - name: build doc
      run: make docs
      #Web-version
    - name: Install packages for webver
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y make
    - name: Setup Emscripten SDK
      uses: mymindstorm/setup-emsdk@v14
    - name: Verify Emscripten
      run: emcc -v
    - name: Build SDL3 port for Emscripten
      run: embuilder build sdl3
    - name: Build web-version
      run: make webver
      #Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feat/webver') }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
