name: Build Web Version

on: [push, pull_request, workflow_call]

jobs:
  build-webver:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y python3 cmake make

    - name: Setup Emscripten SDK
      uses: mymindstorm/setup-emsdk@v14

    - name: Verify Emscripten
      run: emcc -v
        
    - name: Build SDL3 port for Emscripten
      run: embuilder build sdl3

    - name: Build web demo
      #working-directory: demo/sdl3_renderer
      run: make webver

    - name: Upload webversion artifact
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: doc/html
